### ISSUE TITLE
Upgrade to 2.9.0 caused loading bar to not appear in production builds of addons.mozilla.org

### ISSUE THREAD

**Issue by tofumatt** [mironov/react-redux-loading-bar#39] opened 2017-05-18 17:36 UTC
Howdy there!

Sorry for the issue with minimal info but I looked at what I think is [the diff between `2.8.2...2.9.0`](https://github.com/mironov/react-redux-loading-bar/compare/762fa369691aab52df550b1a2b2ee742b2b70b2a...cfb35014376fbd7c01e2a04f5b1a04573a46113a) and couldn't find much that would indicate a breaking change.

But our production builds which include serving the site with these CSP rules:

```
default-src 'none'; base-uri 'self'; child-src 'none'; connect-src https://addons.mozilla.org https://sentry.prod.mozaws.net; form-action 'self'; frame-src 'none'; img-src 'self' data: https://addons.cdn.mozilla.net https://addons-amo.cdn.mozilla.net https://www.google-analytics.com; media-src 'none'; object-src 'none'; script-src https://addons-amo.cdn.mozilla.net https://www.google-analytics.com/analytics.js; style-src https://addons-amo.cdn.mozilla.net 'sha256-DiZjxuHvKi7pvUQCxCVyk1kAFJEUWe+jf6HWMI5agj4='; report-uri /__cspreport__; font-src https://addons-amo.cdn.mozilla.net
```

do not display the loading bar once updated to `2.9.0`. Downgrading to `2.8.2` works fine. I can point you to our code usage if that would help, but I'm filing here because I'm a bit lost and I'm not sure why the loading bar stopped working.

https://github.com/mozilla/addons-frontend/issues/2395

**Comment by mironov** [comment] 2017-05-21 01:07
@tofumatt Thanks for the bug report, it was a tricky one!

The problem can be reproduced with Server Side Rendering and strict Content Security Policy for styles (i.e. `style-src` doesn't have `'unsafe-inline'`).

Some context:
I intentionally haven't introduced any dependencies or CSS files into the loading bar to keep it lightweight and easy to configure. It can be used without any preprocessors.

When the browser loads an SSR page, it blocks inline styles on its elements. Once Loading Bar kicks in, it alters its inline styles to emulate progress. Turned out that style attributes that were initially blocked will not be applied to the element unless they change.

Inline styles in 2.8.2:
```js
  var style = {
    width: this.state.percent + '%',
    transition: 'width ' + ANIMATION_TIME + 'ms linear',
    opacity: '1'
  }

  if (this.shouldShow()) {
    style.opacity = '1';
  } else {
    style.opacity = '0';
  }
```

`width` and `opacity` are dynamic attributes. The `transition` attribute will never be applied to the element as it was initially blocked by CSP and never changes. However, the animation will be shown because `width` and `opacity` combined with custom CSS class for color, height, and positioning is enough to make it work.

Inline styles in 2.9.0:
```js
  var style = {
    opacity: '1',
    transform: 'scaleX(' + this.state.percent / 100 + ')',
    transformOrigin: 'left',
    transition: 'transform ' + ANIMATION_TIME + 'ms linear',
    width: '100%',
    willChange: 'transform, opacity'
  }

  if (this.shouldShow()) {
    style.opacity = '1';
  } else {
    style.opacity = '0';
  }
```

Static styles as `transformOrigin`, `transition`, `width`, `willChange` will be ignored.
That change in animation mechanics in 2.9.0 revealed the problem.

Please give `v2.9.1` a try.
It renders a placeholder on the server side and replaces it with the actual Loading Bar with proper styles after mount. That should not trigger CSP warnings on initial page render and fix the animation.

**Comment by mironov** [comment] 2017-05-28 17:54
@tofumatt I'm going to close this issue as I think it is resolved in v2.9.1.
Feel free to reopen if the fix didn't work for you.

**Closed by mironov** 2017-05-28 17:54 UTC

**Comment by tofumatt** [comment] 2017-05-28 23:40
Will do, sorry I haven't tried the fix sooner and thanks so much for your work looking into it and fixing it with the little info I gave! Just been busy with another part of the project but I'll try it this week hopefully 😄

**Comment by tofumatt** [comment] 2017-05-30 22:13
Just wanted to let you know I tested this on our production build (locally) and it seems to have worked perfectly. Thanks so much for tracking this down and the quick fix! 😄
