### ISSUE TITLE
Event loading-bar/SHOW is being triggered but the component still hidden

### ISSUE THREAD

**Issue by bqueiroz** [mironov/react-redux-loading-bar#40] opened 2017-05-19 20:37 UTC
I'm trying to use this component but for some reason it looks like the component is not reacting to the state, the events are triggered but the bar doesn't shows up.. I'm using version `2.9.0` btw and react `15.5.4`...

my setup:
```
const middleware = applyMiddleware(
    routerMiddleware(history),
    promise(),
    thunk,
    loadingBarMiddleware(),
    createLogger()
);
const store = createStore(
    combineReducers({
       ...
        loadingBar,
        router
    }),
    middleware
);

...

ReactDOM.render(
    (
        <Provider store={store}>
            <ConnectedRouter history={history}>
                <div id="app">
                    <LoadingBar showFastActions className="progress-bar"/>
                    ...
                </div>
            </ConnectedRouter>
        </Provider>
    ),
    document.getElementById('root')
);

```

UPDATE:

not even with saga and triggering the events manually it doesn't seems to work.

**Comment by mironov** [comment] 2017-05-20 13:44
@bqueiroz Thank you for the report. It looks like something overlaps the loading bar.
Could you check in Web Inspector that the loading bar is making progress?
It should look like it is on the video: http://d.pr/v/eeVUm

If inline `style` is changing, then please set `z-index` on the loading bar or `position` it as it's appropriate.

You have set you own `className` on loading bar. Please keep in mind that loading bar [doesn't set any positioning](https://github.com/mironov/react-redux-loading-bar/blob/master/src/loading_bar.js#L137-L142) in that case as it's assuming that you will do that in CSS. You can also try to remove custom CSS class to see if that is the problem.

**Comment by mironov** [comment] 2017-05-21 01:09
@bqueiroz If you use server side rendering, please give v2.9.1 a try. It includes a fix for SSR with strict CSP (#39).

**Comment by bqueiroz** [comment] 2017-05-22 12:07
@mironov that was the first thing I did, checking if the had z-index:9999, I'm not using ssr... But right now I'm using a custom made one that I hooked up in the XHR events, I will change to use it again with v2.9.1 and let you know, thanks for the reply =]

**Comment by mironov** [comment] 2017-05-28 17:55
@bqueiroz I'm going to close the issue as I think the problem should be with Loading Bar CSS positioning. Feel free to reopen the issue if you have any additional info.

**Closed by mironov** 2017-05-28 17:55 UTC

**Comment by ramjak** [comment] 2017-07-20 02:40
I have the same issue. loading-bar/SHOW event has been triggered, but the opacity still 0

**Comment by mironov** [comment] 2017-07-20 08:05
@ramjak Was there a `loading-bar/HIDE` event? Could you make a quick example that reproduces the problem?

**Comment by gonnarule** [comment] 2017-07-25 14:13
Same issue here. Trying to get this to work. I have 'loading-bar/SHOW' and X sec after 'loading-bar/HIDE' actions in the redux inspector. When inspecting html, I see the component which is 0x3 px sized (0 width), even if style is width:100%. Opacity stays at 0, width / scaleX doesn't change (throttling network to have plenty of second to inspect html, but nothing occurs... Using thunk + promiseMiddleware.

**Comment by mparker11** [comment] 2017-07-25 17:59
Has anyone found the solution to this? I'm using the dispatch method and as everyone as stated, the opacity nor the scale never changes from zero.

**Comment by mparker11** [comment] 2017-07-25 18:26
I figured it out. In learning redux, I have still been a bit confused by this concept but in line 243 of loading_bar.js, the current line is `loading: state.loadingBar` which is `undefined`.

When I changed it to `loading: state.get('loadingBar')` (using the get method), the value is returned as expected. I have run into this problem before, using the object notation instead of redux's get method. I'm not sure when each should be used, but in this case, `get` seems to work.

**Comment by mironov** [comment] 2017-07-25 20:03
@mparker11 Hey are you using `immutable-js` by any chance? Is your Redux store is an Immutable Map?

**Comment by mparker11** [comment] 2017-07-25 22:06
@mironov Ah, I didn't even think about that! It slipped my mind because I'm using [React Boilerplate](https://github.com/react-boilerplate/react-boilerplate). I guess you can totally ignore that pull request. It works for me now! Thanks! I just learned more on when to use `get` vs the dot notation as well.

**Comment by mironov** [comment] 2017-07-26 08:02
@mparker11 Yep, that's it. React Boilerplate seems to include the immutable store: https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/js/immutablejs.md

In that case you can import the immutable version of the Loading Bar.
Change
```
import LoadingBar from 'react-redux-loading-bar'
```

to

```
import { ImmutableLoadingBar as LoadingBar } from 'react-redux-loading-bar'
```
