### ISSUE TITLE
Is this supposed to work with server-side rendering?

### ISSUE THREAD

**Issue by vhpoet** [mironov/react-redux-loading-bar#30] opened 2017-02-14 00:42 UTC
I get this exception 

```
Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op. Please check the code for the LoadingBar component.
```

Thanks

**Comment by mironov** [comment] 2017-02-19 14:12
Hey @vhpoet, thank you for letting me know about this error. I just published the v2.6.6 that should fix this bug. Please let me know if it works because I don't use server side rendering yet.

**Comment by vhpoet** [comment] 2017-02-21 19:41
@mironov almost. Checking on 2.7.0 I don't get the exception anymore, but there are still a couple of problems. 
- I get my initial state with `loadingBar:2` which I'm guessing is happening because the server side requests also count. The problem is avoided when I only conditionally use the `loadingBarMiddleware` only if the browser is a browser.
- The animation never stops, it goes from 0 to 100 and then back to 0 and so on.

**Comment by mironov** [comment] 2017-02-26 14:06
@vhpoet Could you help me with reproducing the problem?

I took one of universal boilerplates and installed the Loading Bar: https://github.com/mironov/react-redux-universal-hot-example/commit/fb53a2e995b562fa76665ed71ef7238f7550a8ad
Can't reproduce described issues.

**Comment by mironov** [comment] 2017-03-04 20:53
@vhpoet I published v2.7.1 that might fix at least the animation problem. Please let me know if it fixes your issues.

**Comment by vhpoet** [comment] 2017-03-07 00:14
@mironov will check and let you know, thanks!

**Comment by vhpoet** [comment] 2017-03-07 00:38
@mironov animation thing is fixed, but the other issue is not resolved. This might be a problem with my local environment tho, don't have much time to debug right now, so will just add the middleware on the client only.

**Comment by mironov** [comment] 2017-03-07 14:53
@vhpoet Great to hear. I'm going to close this issue for now as I can't reproduce the remaining problem. Please feel free to reopen it if you find additional details.

**Closed by mironov** 2017-03-07 14:53 UTC
